#!/bin/sh

FONT_DIR="/usr/share/fonts /usr/share/fonts/X11 /usr/X11R6/lib/X11/fonts /usr/lib/X11/fonts /usr/share/fonts/truetype/openoffice"

[ -d /usr/lib/xorg/modules ] && options="--x11r7-layout" || options=""

if [ "$UID" -ne 0 ]; then
	[ -x /usr/bin/kanotix-su ] && DISPLAY="" exec kanotix-su "$0" "$@"
	
	echo Error: You must be root to run this script!
	exit 1
fi

for dir in $FONT_DIR; do
	if [ -d "$dir" ]; then
		cd /
		find "$dir" -name *ttf |while read x; do dirname "$x"; done|sort|uniq|while read x; do
			echo ttf processing... "$x"
			cd "$x"
			rm -f encodings.dir fonts.alias fonts.dir fonts.scale
			if [ "$1" != "-e" ]; then
				mkttfdir
			else
				mkttfdir -e
			fi
		done

		cd /
		find "$dir" -name *pcf.gz|while read x; do dirname "$x"; done|sort|uniq|while read x; do
			echo pcf processing... "$x"
			cd "$x"
			rm -f encodings.dir fonts.alias fonts.dir fonts.scale
			update-fonts-scale "$options"	$(basename $x)
			update-fonts-dir "$options"	$(basename $x)
			update-fonts-alias "$options" 	$(basename $x)
		done
	fi
done

fc-cache -f

