#!/bin/sh

if [ "$UID" -ne 0 ]; then
	[ -x /usr/bin/kanotix-su ] && DISPLAY="" exec kanotix-su "$0" "$@"
	
	echo Error: You must be root to run this script!
	exit 1
fi

for dir in /usr/share/fonts /usr/X11R6/lib/X11/fonts /usr/lib/X11/fonts; do
	cd /
	find "$dir" -name *ttf |while read x; do dirname "$x"; done|sort|uniq|while read x; do
		echo ttf processing... "$x"
		cd "$x"
		rm -f encodings.dir fonts.alias fonts.dir fonts.scale
		if [ "$1" != "-e" ]; then
			mkttfdir
		else
			mkttfdir -e
		fi
	done

	cd /
	find "$dir" -name *pcf.gz|while read x; do dirname "$x"; done|sort|uniq|while read x; do
		echo pcf processing... "$x"
		cd "$x"
		rm -f encodings.dir fonts.alias fonts.dir fonts.scale
		update-fonts-scale $(basename $x)
		update-fonts-dir   $(basename $x)
		update-fonts-alias $(basename $x)
	done
done

fc-cache -f

